### PR TITLE
WIP: Nunjucks adapter

### PR DESCRIPTION
**Pull request by nporteschaikin**
I've added support for [Nunjucks](https://github.com/jlongster/nunjucks), a dynamic template engine with a lot of goodies you've come to expect from template engines (loops, includes, blocks, etc.).  

Unfortunately, the ["should render with client side helpers" test](https://github.com/carrot/accord/blob/nunjucks/test/test.coffee#L73) isn't passing yet.  There seems to be an [issue](https://github.com/jlongster/nunjucks/issues/129) with the client-side JavaScript.

I'll also be writing thorough documentation tomorrow.  Let me know what y'all think :+1:

### CODE REVIEW

**Comment by jenius** [comment]
I think this should be closed out at this point if we can't make it happen

**Comment by jenius** [comment]
Closing this due to inactivity. Would love to get it merged but it doesn't seem like anyone is working on it, sadly.

**Comment by heyallan** [comment]
No way :(
@nporteschaikin please don't give up!
Let me know if I can be of any help.

**Comment by nporteschaikin** [comment]
@heyallan My friend, it's not a matter of giving up!  We were waiting on an update from Mozilla.  I'll check it out again.  :)

**Comment by heyallan** [comment]
When I say “don't  give up” I mean “don't close the issue”. Even if it goes slow, It's still relevant.
:+1:

**Pull request closed without merging**
