### PR TITLE
Use semver in devDependencies: `latest` -> `*`

### PR DESCRIPTION
**Pull request by davej**
The `latest` version is simply the last version that was published to NPM. For example, this could be a pre-release version or I believe it could even be a bugfix to an old version of the module.

I think `*` is probably what is wanted as it will install the latest stable release according to semver. You could also use `>= 0`, which does the same thing.

### CODE REVIEW

**Comment by jenius** [comment]
Actually I do not support prereleases with accord, only stable releases. Prereleases are not intended for the masses, are usually unstable, and are not installed unless by special attention. I actually used to have `*` here and it caused issues with the tests because it installed unstable prereleases which broke things, but which nobody was using, so I changed it to latest a while ago.

**Comment by davej** [comment]
I think you misunderstood. `*` Should never install pre-releases.
Currently `latest` *might* install pre-releases if the most recently published version happens to be a pre-release. This is the issue in #130.

For example:
```
> var semver = require('semver')
> semver.maxSatisfying(['1.1.0-rc.1', '1.1.0-rc.2'], '*')
null
> semver.maxSatisfying(['1.0.0', '1.1.0-rc.1', '1.1.0-rc.2'], '*')
'1.0.0'
```

Perhaps the issues, that you were having with `*` were related to an old version of NPM (i.e. NPM1)? The `*` constraint should never install a pre-release (at least not in NPM2 or NPM3, I haven't tested NPM1).

**Comment by jenius** [comment]
Yeah maybe this was a thing with npm1? I tested this thoroughly -- `latest` would only install the latest stable release. Unless the author manually tagged `latest` to a prerelease, which would be insane, it would never happen. And `*` would consistently install the most recent release. If you have tested this and they flipped it in newer versions of npm (which would be confusing but such is life), then ok maybe we need to switch it?

But I still would not understand why that change was made. `latest` is a tag specifically meant to represent the latest stable release, and `*` in programming typically represents "everything", as in globstar. Any author should have their latest stable release tagged as `stable`, in fact npm does this autmatically for you unless you are publishing a prerelease. So I feel like exceptions here might be coming from a rare author doing something weird...

**Comment by davej** [comment]
Well, this was spawned from the typescript PR. So, if you do:
```
npm install typescript-compiler@latest
```

Then it will install `1.4.1-2` which is a pre-release according to semver because it contains a dash character (although it was **not** intended to be a pre-release by the author). This is why I created this PR. If you do `npm install typescript-compiler@*` (or just `npm install typescript-compiler`) then it will install `1.4.1` which is the latest stable release according to semver.

Regarding the star. Yeah I agree, ideally I think it's better to have a version number with a caret, as it's more explicit:
```
"babel": "^5.8.29"
// or just
"babel": "^5"
```

**Comment by jenius** [comment]
Ah really? That's a major change in how npm works since the last time I checked, which was npm1 I suppose. In npm1, when you run `npm install xxx`, it will go and get the `latest` tag, then install that version. So for that reason I used `latest`, which made sense.

However if what you say is correct, npm's internals must have changed a good bit. Do you know what is actually happening internally? I poked around the repo a bit but didn't find anything and I have to run now. For the tests I basically always want to install the way it happens when a user runs `npm install xxx`, because if the tests fail because of a version bump, that's good, it should be fixed. I don't want to manually bump every version for the tests every time.

**Comment by davej** [comment]
> Ah really? That's a major change in how npm works since the last time I checked, which was npm1 I suppose. In npm1, when you run npm install xxx, it will go and get the latest tag, then install that version. So for that reason I used latest, which made sense.

> However if what you say is correct, npm's internals must have changed a good bit. Do you know what is actually happening internally? I poked around the repo a bit but didn't find anything and I have to run now. 

Sorry, I'm not sure what has changed or how it works internally. `typescript-compiler@1.4.1-2` is actually tagged with the `latest` tag. AFAIK publishing a package **always** sets it to the `latest` tag regardless of whether it's a pre-release or not, I'm not sure if this behavior has changed from npm1 though. I'm confident that the statements I've made about npm2 and npm3 are correct though.

> For the tests I basically always want to install the way it happens when a user runs npm install xxx, because if the tests fail because of a version bump, that's good, it should be fixed. I don't want to manually bump every version for the tests every time.

Sounds like [Greenkeeper](http://greenkeeper.io/) is what you need for this. When new versions of dependencies are released then it will run your CI tests and create a PR (even when the deps are outside of the package range specified in your `package.json`), if the tests pass then you can just merge, otherwise you can track the issue in the PR. I've been using it on my projects for a while now, it's fantastic. Free for open source too.

It seems like explicit version ranges with the caret (^) for compatible versions is the way to go. Then use Greenkeeper to track changes to dependencies.

**Comment by davej** [comment]
> Publishing a package sets the "latest" tag to the published version unless the --tag option is used. For example, npm publish --tag=beta.

— https://docs.npmjs.com/cli/dist-tag

**Comment by davej** [comment]
BTW, let me know if you'd like me to do a PR for caret version deps and Greenkeeper.

**Comment by jenius** [comment]
Yeah, so when you publish a prerelease you are [supposed to use --tag](http://carrot.is/coding/npm_prerelease), otherwise this is a mistake.

But yeah I use greenkeeper for a couple other projects and I think you're right that this one would be a good call. I'll activate it now :+1:

**Comment by davej** [comment]
Yeah, I agree that you are supposed to. I just think some people either don't know or often forget and using semver is probably more reliable than a tag.

Anyway this is a bit of a bikeshed and adding greenkeeper will streamline the process for sure. Thanks for your great work! :+1: :-)

**Pull request closed without merging**
