### PR TITLE
rename 6to5 to Babel

### PR DESCRIPTION
**Pull request by hhsnopek**
6to5 was recently renamed to Babel: https://github.com/babel/babel/issues/780
Note there is also a reference update list which we're listed under, this would take care of that :smile:

### CODE REVIEW

**Comment by Munter** [comment]
Won't this break existing usage if merged? I would think accord should have both 6to5 and babel simultaneously in order to maintain backwards compatibility for existing users

**Comment by hhsnopek** [comment]
Technically yes, but considering 6to5 is officially babel (4.0.x has been released) it's already breaking everything using it

**Comment by Munter** [comment]
Not if people have pinned any version below 4.0 of 6to5. Or is the 6to5 package also being completely unpublished and babel released with all previous 6to5 versions?

**Comment by hhsnopek** [comment]
Well if people are using anything below Babel 4.0 they could just lock Accord to 0.14.4 as well, I believe 6to5 will remain on npm for people using it... Otherwise it's just gonna become old and most people will upgrade or use Babel in the future

**Comment by Munter** [comment]
This is always the problem with these wrapper packages. Should accord increment the major version or not. I've had exactly the same dilemma in some other convenience wrapper tools. Anyway, now the potential problem has been highlighted. I just wanted to make sure this wasn't merged in without giving it a second thought

**Comment by hhsnopek** [comment]
fixed in f78a6f136bcb10358f8ce543dd64dc325fed1cd3

**Comment by jenius** [comment]
Ah sorry didn't see this earlier! But yeah @Munter I agree, still trying to think about how to handle breaking changes. It's a pretty tough issue. For now we are just moving forward with the latest versions of everything...

**Pull request closed without merging**
