### PR TITLE
misc

### PR DESCRIPTION
**Pull request by slang800**

### CODE REVIEW

**Comment by jenius** [comment]
Ok so other than comments made here, I'd be ok with merging this. I'd rather not merge the breaking `clientHelpers` return promises piece yet if possible though.

**Comment by jenius** [comment]
Ok so this one is only waiting on the promise being returned from client helpers to be cut into a separate PR before it can be merged

**Comment by slang800** [comment]
The promise being returned is split into a separate commit. But, further changes in #47 depend upon that behaviour, so it can't be delayed too much. The best course of action would just be to finish all of these interface changes before releasing a new version.

**Comment by jenius** [comment]
This needs to be rebased before merge as well

**Comment by slang800** [comment]
Idk if we should attempt a rebase. The commits that are in front of it involve an implementation of source-maps (which is already covered later in #47), and a switch to chai (which would be hell to rebase on top of).

There's some stuff that should be used in those commits, but the majority is already covered by #47

**Comment by jenius** [comment]
Welp, we can rebase or we can not merge it. Up to you...

**Comment by slang800** [comment]
Or we could revert those commits and then merge on top of that.

And I assume you mean you're "[not] going to straight out accept a rewrite" (based on the "nor"): I don't plan on doing it as a single pull-request because that would be hard to review. But I do want to do all the interface changes within the same version bump, and I do want to get this done as quickly as possible so my fork doesn't diverge even further.

**Comment by jenius** [comment]
Reverting the commits is not an option. If I'm going to accept a pull request here, it has to be built incrementally on top of the existing code. This is not going to be a quick and easy process, and I'm not going to accept all your changes without any questions or revisions.

The best way for you to do this is, as mentioned previously, to break down your changes into small, contained pull requests, one per feature, that build on top of the existing code. Does that seem reasonable/possible?

**Comment by slang800** [comment]
Sorry, I mean a "revert-commit", not doing a hard-reset to before the sourcemap thing was merged... just adding a commit that effectively reverts the sourcemap implementation to make way for the new one.

**Comment by jenius** [comment]
There will be no reverted commits. I really thought that was clear in my previous comments. If you are unable to build on top of the current code, I have to say no to this pull request, I'm sorry.

**Comment by slang800** [comment]
What's wrong with reverting? The end result would be the same anyway, and so long as the commit history is clean, it shouldn't matter how we reach that point, right?

**Comment by jenius** [comment]
In order to get all your changes merged, it's going to take a very long time. I would like to make these changes incrementally to the project, so that we are slowly adding improvements rather than immediately dropping one massive change. In order to do that, I would like to be able to merge small, contained pull requests into master over time, until we get through all the things you want to change. In order to do this, I need to have your pull requests such that they are up to date and able to be merged into the current codebase.

I do understand that this is not your preference, and you'd like to continue discussing this until we both come to an agreement on your point of view. However, I do not agree with your point of view, and I'm not willing to spend any more time discussing this issue, as I have other things I need to be working on. For that reason I offer you two choices:

1) Rebase your pull requests such that they are merge-able with the current codebase, then we will go through them and get as many as we can merged.
2) Fork the project and work on it entirely on your own, then you don't have to debate anything with me at all.

If you respond here asking me reconsider my position on this issue, I will not respond further, I'm sorry. We're either working through small, contained, merge-able pull requests, or we are not working on anything.

**Comment by slang800** [comment]
For option 2, would we then switch roots over to use the fork? If not, I don't see how that's a viable option.

**Comment by jenius** [comment]
No, and you're right, it doesn't seem like a viable option to me. But it's an option. Your choice.

**Comment by slang800** [comment]
This PR is mergeable now... There are a ton of merge conflicts because of the divergence, so I just removed those commits to deal with them later.

**Comment by jenius** [comment]
Checking in here. Are we breaking this out to multiple PRs or should this be closed?

**Comment by slang800** [comment]
Feel free to cherry-pick whatever changes you like in here. I don't have much time to work on this atm.

**Comment by jenius** [comment]
Ok, I'm going to close this out then. If it's under active development again we can re-open.

**Pull request closed without merging**
