### PR TITLE
Sass entry file is the first (not last) file in sources array

### PR DESCRIPTION
**Pull request by davej**
Based on my testing with node-sass 3.4.2, the entry file is the first file in the sources array.
The previous code assumed that it was the last item.

### CODE REVIEW

**Comment by jenius** [comment]
Ah ok, is this the case in all version `3.x` ranges? If not we need to segment out our support a bit, and if not then we can merge it. Could you run a couple basic tests?

**Comment by davej** [comment]
Entry file is the first file in node-sass 3.3.3 too (although the ordering of later files is changed). It's difficult to test other versions of node-sass with my project because they're not compatible with Node 4+.

I'm not sure what the reason is for changing the entry file? In my testing `data.sourcemap.sources[0]` is always the same as `options.file`, but I'm sure it's there to cover an edge case, do you know why it's there?

```CoffeeScript
if data.sourcemap.sources[0]
  data.sourcemap.sources[0] = options.file
```

**Comment by jenius** [comment]
If I'm not mistaken when that line was originally written, the `sources` array was populated incorrectly, so I had to push in the correct filename so that when the sourcemap was extracted it would point to the right place. If it works now without making this janky change, than I'm more than happy to remove that line!

**Comment by davej** [comment]
> If it works now without making this janky change, than I'm more than happy to remove that line!

Sounds good to me :+1:

**Comment by jenius** [comment]
The only issue is what happens with older versions here. Is there any chance you could test this with a `3.0` range version of sass and make sure that it doesn't break down? If it does we need to split out the code so backwards versions are covered too.

**Comment by davej** [comment]
Ok, tested 3.0 and output is consistent with 3.4.
There is a different issue though.
Sourcemap paths are relative to the project root (presumably `process.cwd()`), whereas `options.file` is absolute.

i.e..
```javascript
console.log(options.file); // -> '/Users/dave/github/accord/test/fixtures/scss/external.scss'
console.log(data.sourcemap.sources[0]); // -> 'test/fixtures/scss/external.scss'
```

This wasn't found in the tests because the tests only check the first item in the array (which is an absolute path).

So before this change, the final sources looked like:
```js
[ '/Users/dave/github/accord/test/fixtures/scss/external.scss', 'test/fixtures/scss/_mixin_lib.scss' ]
```

Now it looks like:
```js
[ 'test/fixtures/scss/external.scss', 'test/fixtures/scss/_mixin_lib.scss' ]
```

To be consistent with sourcemap paths elsewhere in accord I guess we should map over the array and make paths absolute?

**Comment by jenius** [comment]
Ah nice, good catch, and great investigation. Thanks for taking this time to check this out!

Yeah we should have all the paths being absolute for sure. Accord automatically inlines sources with the sourcemaps to ensure that there's no shenanigans with paths shifting around, so having absolute paths is the best way to make sure everything is inline.

**Comment by davej** [comment]
Ok, cool. Let me know if you want me to do a PR for it.

On a side note, since you mentioned sourcesContent. Do you know if it adds much overhead in terms of compilation performance? I don't need it for my purposes (https://github.com/davej/piggy-in-the-middle & https://github.com/davej/baconize) because I convert the paths to relative paths and they are always predictable. If inlining adds to the compile time (because of extra I/O) then I would be interested in doing a PR that makes the feature optional.

**Comment by jenius** [comment]
Would love that! Thanks :+1:

I haven't done a perf measurement on it yet. I mean it certainly is adding extra i/o as it's reading files, but this happens in separate processes async and I have never seen a noticeable slowdown because of it. The problem is basically that accord has to handle quite a number of different languages, and many of them are not consistent in the way they shoot back the sources array. Accord's purpose is to bring consistency to the output between languages so that users can switch around without encountering major issues, so I just went for the most consistent method, which was inlining sources.

If someone notices a major perf hit and submits a PR that would consistently make all languages output relative paths in the sources array I would happily accept this though!

**Comment by davej** [comment]
See #126 instead.

**Pull request closed without merging**
