### PR TITLE
attempt at allowing raw defines for Stylus

### PR DESCRIPTION
**Pull request by acidjazz**
grunt fix:
https://github.com/gruntjs/grunt-contrib-stylus/issues/100

original reason this was added:
https://github.com/stylus/stylus/issues/1286

### CODE REVIEW

**Comment by jenius** [comment]
Could you add a test case for this por favor? :pray:

**Comment by acidjazz** [comment]
Sorry for the delay @jenius never used mocha before, test added!

**Comment by jenius** [comment]
Perfect, looks great! Hope it was a smooth experience for the first time :grinning:

**Comment by acidjazz** [comment]
Thanks! it was, I'm a mocha fan now, any potential ETA on a release? I have an inception-type issue of modules breaking from this :)

**Comment by jenius** [comment]
Just released :grinning:

**Comment by acidjazz** [comment]
:-D

**Pull request merged**
