### PR TITLE
Convert SCSS sourcemap source to absolute paths

### PR DESCRIPTION
**Pull request by davej**
This is basically #119 but without the erroneous commits.

I'm not 100% sure that `process.cwd()` is the correct way to do this, it works in my testing but perhaps there are cases or environments where it might not work?

### CODE REVIEW

**Comment by davej** [comment]
Yeah, as I said in my comment above, I'm not sure that it will always be correct. I did a quick code search on (node/lib)-sass but couldn't figure out exactly how the relative paths are calculated.

**Comment by jenius** [comment]
Hmm, I think we need to find a way to make that more accurate before pulling...

**Comment by davej** [comment]
See updated PR, of course this makes the assumption that the first source will always be the entry file

**Comment by jenius** [comment]
I guess that's as close as we will get... any other ideas or things you want to add here? If not I'd say we're ok to merge

**Comment by davej** [comment]
I'll open an issue on libsass to figure out how the relative path is calulated. The more I think about it, `process.cwd` might be correct, I'm not sure how else you would choose the dir to resolve from.

**Comment by davej** [comment]
Ok. I think I've finally stumbled upon a reliable solution. Passing in the full path (instead of just the filename) to `outFile` gives sourcemap sources relative to `outFile`. this allows us to reliably convert the relative file paths to absolute.

**Comment by jenius** [comment]
Awesome! This looks great. Squash the fix commits and we're ready to merge up I think, unless you have any other thoughts or concerns

**Comment by davej** [comment]
Cool, commits squashed.

**Comment by jenius** [comment]
:+1: thanks for your good work on this! :tada:

**Pull request merged**
