### PR TITLE
Add jade2php adapter

### PR DESCRIPTION
**Pull request by FranzSkuffka**
@jenius can you take a look at this?

### CODE REVIEW

**Comment by jenius** [comment]
Looks much better! Are there any other jade2php features in particular that you want to verify are working through a test, or just the imports? Maybe a little block of php or something?

**Comment by FranzSkuffka** [comment]
Will look into it soon. I have a feeling that the tests I created are a little smelly. Maybe I can recycle some of the jade2php unit tests. Thanks for the feedback.

**Comment by jenius** [comment]
Ping!

**Comment by FranzSkuffka** [comment]
Currently I need to focus on different things, I will come back once I find the time.

**Comment by FranzSkuffka** [comment]
So right now I am learning how to use promises within my flextractor project. So once I am done with this (~30 days) I might have some time to integrate this adapter.

**Comment by jenius** [comment]
Awesome! Excited to see it

**Pull request closed without merging**
